
export const AUTH_SIGN_IN_ACTION = "AUTH_SIGN_IN_ACTION";
export const AUTH_SIGN_OUT_ACTION = "AUTH_SIGN_OUT_ACTION";

export const AUTH_SIGN_IN_REQUEST_SIGNAL = "AUTH_SIGN_IN_REQUEST_SIGNAL";
export const AUTH_SIGN_IN_SUCCESS_SIGNAL = "AUTH_SIGN_IN_SUCCESS_SIGNAL";
export const AUTH_SIGN_IN_FAILURE_SIGNAL = "AUTH_SIGN_IN_FAILURE_SIGNAL";
export const AUTH_SIGN_OUT_SIGNAL = "AUTH_SIGN_OUT_SIGNAL";