export default {
  logo: require("assets/logo.png"),
  ghcs200: require("assets/img/ghcs-200.png"),
  ghcs300: require("assets/img/ghcs-300.png"),
  ghcsNoTitle300: require("assets/img/ghcs-no-title-300.png"),
  authBG: require("assets/img/auth-bg.png"),
  frontTopLeft: require("assets/img/front-top-left.png"),
  frontTopRight: require("assets/img/front-top-right.png"),
  post: require("assets/img/post.png"),
  news: require("assets/img/news.png"),
  video: require("assets/img/video.png"),
  questionnaire: require("assets/img/questionnaire.png"),
  vote: require("assets/img/vote.png"),
  contactUs: require("assets/img/contact-us.png"),
  consultants: require("assets/img/consultants.png"),
  about: require("assets/img/about.png"),
  vision: require("assets/img/vision.png"),
  mission: require("assets/img/mission.png"),
  goal: require("assets/img/goal.png"),
  postListitem: require("assets/img/post-listitem.png"),
  newsListitem: require("assets/img/news-listitem.png"),
};